version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/src/frontend'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - atipezda
  assignees:
    - atipezda
  commit-message:
    prefix: FRNT_fix_depend
    prefix-development: chore
    include: scope
- package-ecosystem: npm
  directory: '/src/backend'
  schedule:
    interval: daily
    time: '00:10'
  open-pull-requests-limit: 10
  reviewers:
    - atipezda
  assignees:
    - atipezda
  commit-message:
    prefix: Back_fix_depend
    prefix-development: chore
    include: scope
